//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharpMod.Exceptions {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SharpModExceptionResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharpModExceptionResources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SharpMod.Exceptions.SharpModExceptionResources", typeof(SharpModExceptionResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error allocating structure.
        /// </summary>
        internal static string ERROR_ALLOC_STRUCT {
            get {
                return ResourceManager.GetString("ERROR_ALLOC_STRUCT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Device number out of range.
        /// </summary>
        internal static string ERROR_DEVICE_NUMBER_OUT_OF_RANGE {
            get {
                return ResourceManager.GetString("ERROR_DEVICE_NUMBER_OUT_OF_RANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Driver error.
        /// </summary>
        internal static string ERROR_DRIVER {
            get {
                return ResourceManager.GetString("ERROR_DRIVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error loading header.
        /// </summary>
        internal static string ERROR_LOADING_HEADER {
            get {
                return ResourceManager.GetString("ERROR_LOADING_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error loading pattern.
        /// </summary>
        internal static string ERROR_LOADING_PATTERN {
            get {
                return ResourceManager.GetString("ERROR_LOADING_PATTERN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error loading sampleinfo.
        /// </summary>
        internal static string ERROR_LOADING_SAMPLEINFO {
            get {
                return ResourceManager.GetString("ERROR_LOADING_SAMPLEINFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error loading track.
        /// </summary>
        internal static string ERROR_LOADING_TRACK {
            get {
                return ResourceManager.GetString("ERROR_LOADING_TRACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unknown module format.
        /// </summary>
        internal static string ERROR_NOT_A_MODULE {
            get {
                return ResourceManager.GetString("ERROR_NOT_A_MODULE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error opening file.
        /// </summary>
        internal static string ERROR_OPENING_FILE {
            get {
                return ResourceManager.GetString("ERROR_OPENING_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Out of sample-handles.
        /// </summary>
        internal static string ERROR_OUT_OF_HANDLES {
            get {
                return ResourceManager.GetString("ERROR_OUT_OF_HANDLES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Couldn&apos;t open output file.
        /// </summary>
        internal static string ERROR_OUTPUT_FILE {
            get {
                return ResourceManager.GetString("ERROR_OUTPUT_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sample too big, out of memory.
        /// </summary>
        internal static string ERROR_SAMPLE_TOO_BIG {
            get {
                return ResourceManager.GetString("ERROR_SAMPLE_TOO_BIG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You don&apos;t have any of the supported sound-devices.
        /// </summary>
        internal static string ERROR_UNSUPPORTED_SOUND_DEVICE {
            get {
                return ResourceManager.GetString("ERROR_UNSUPPORTED_SOUND_DEVICE", resourceCulture);
            }
        }
    }
}
